### ISSUE TITLE
errors when run the demo

### ISSUE THREAD

**Issue by tensorboy** [nishiwen1214/ChatReviewer#6]
Traceback (most recent call last):
  File "/Users/wangpengan/Desktop/education/ChatReviewer/chat_reviewer.py", line 181, in <module>
    main(args=args)    
  File "/Users/wangpengan/Desktop/education/ChatReviewer/chat_reviewer.py", line 158, in main
    paper_list.append(Paper(path=args.paper_path))            
  File "/Users/wangpengan/Desktop/education/ChatReviewer/get_paper_from_pdf.py", line 21, in __init__
    self.parse_pdf()            
  File "/Users/wangpengan/Desktop/education/ChatReviewer/get_paper_from_pdf.py", line 33, in parse_pdf
    self.extract_section_infomation()
  File "/Users/wangpengan/Desktop/education/ChatReviewer/get_paper_from_pdf.py", line 141, in extract_section_infomation
    text = json.dumps(block)
  File "/opt/anaconda3/envs/python39/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/anaconda3/envs/python39/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/anaconda3/envs/python39/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/anaconda3/envs/python39/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

**Comment by merak0514** [comment]
I created a pull request.
