### ISSUE TITLE
错误的最大令牌

### ISSUE THREAD

**Issue by paketecuento** [nishiwen1214/ChatReviewer#8]
在解析一个文件时，我发现以下错误：

```
Traceback (most recent call last):
  File "/Users/paco/Downloads/ChatPaper-main4/chat_reviewer.py", line 181, in <module>
    main(args=args)
  File "/Users/paco/Downloads/ChatPaper-main4/chat_reviewer.py", line 168, in main
    reviewer1.review_by_chatgpt(paper_list=paper_list)
  File "/Users/paco/Downloads/ChatPaper-main4/chat_reviewer.py", line 45, in review_by_chatgpt
    sections_of_interest = self.stage_1(paper)
  File "/Users/paco/Downloads/ChatPaper-main4/chat_reviewer.py", line 100, in stage_1
    response = openai.ChatCompletion.create(
  File "/Users/paco/opt/miniconda3/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/paco/opt/miniconda3/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/paco/opt/miniconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/paco/opt/miniconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/paco/opt/miniconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 8484 tokens. Please reduce the length of the messages.
```

**Comment by paketecuento** [comment]
any update?

**Comment by nishiwen1214** [comment]
可能是因为你论文的abstract太长，已修复。

**Comment by paketecuento** [comment]
Thank you for the update, now I got:
```
Traceback (most recent call last):
  File "/Users/paco/Downloads/ChatReviewer-main5/chat_reviewer.py", line 183, in <module>
    main(args=args)
  File "/Users/paco/Downloads/ChatReviewer-main5/chat_reviewer.py", line 170, in main
    reviewer1.review_by_chatgpt(paper_list=paper_list)
  File "/Users/paco/Downloads/ChatReviewer-main5/chat_reviewer.py", line 45, in review_by_chatgpt
    sections_of_interest = self.stage_1(paper)
  File "/Users/paco/Downloads/ChatReviewer-main5/chat_reviewer.py", line 102, in stage_1
    response = openai.ChatCompletion.create(
  File "/Users/paco/opt/miniconda3/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/paco/opt/miniconda3/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/paco/opt/miniconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/paco/opt/miniconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/paco/opt/miniconda3/lib/python3.9/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: 13296 is not of type 'string' - 'messages.1.content'
```

**Comment by paketecuento** [comment]
thank you again for your effort. I think I found the origin of some problems, mainly the detection of sections. Attached a photo. 

<img width="1011" alt="Captura_de_pantalla_28_3_23__10_48" src="https://user-images.githubusercontent.com/5316182/228183206-134ed690-f779-496e-b332-3e2a3b911d6a.png">

tha abstract is not properly detected and because of this its length is 15000 or so!!

**Comment by nishiwen1214** [comment]
Because the format of abstract is not a title, it is not recognized...
